### ISSUE TITLE
Unable to resolve module `./responsibleTouchArea

### ISSUE THREAD

**Issue by SeanFelipe** [cloudle/ruui#18]
Hello!

I'm getting into RUUI. Love how I can use the browser + hot reload to develop very quickly. Now I'm trying to do an Android build with `react-native run-android` ... I am able to compile the apk, but I get the error below upon load.

The file seems to be there in your RUUI sources ... maybe I need to upgrade my ruui dependencies?

```The development server returned response error code: 500

URL: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js","targetModuleName":"./responsibleTouchArea","message":"Unable to resolve module `./responsibleTouchArea` from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`: The module `./responsibleTouchArea` could not be found from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`. Indeed, none of these files exist:\n\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`","errors":[{"description":"Unable to resolve module `./responsibleTouchArea` from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`: The module `./responsibleTouchArea` could not be found from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`. Indeed, none of these files exist:\n\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`"}],"name":"Error","stack":"Error: Unable to resolve module `./responsibleTouchArea` from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`: The module `./responsibleTouchArea` could not be found from `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/index.js`. Indeed, none of these files exist:\n\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/Users/foo/stuffs/Jubula/jubula-app/node_modules/react-universal-ui/dist/components/responsibleTouchArea/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n    at ModuleResolver.resolveDependency (/Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1122)\n    at ResolutionRequest.resolveDependency (/Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)\n    at DependencyGraph.resolveDependency (/Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)\n    at /Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36\n    at Generator.next (<anonymous>)\n    at step (/Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)\n    at /Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536\n    at new Promise (<anonymous>)\n    at /Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217\n    at addDependency (/Users/foo/stuffs/Jubula/jubula-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)"}
processBundleResult
    BundleDownloader.java:242
access$100
    BundleDownloader.java:41
onResponse
    BundleDownloader.java:208
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818
```

**Comment by SeanFelipe** [comment]
from my package.json ... will see if upgrading fixes

```
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "0.52.2",
    "react-native-drawer": "^2.3.0",
    "react-native-web": "^0.5.4",
    "react-universal-ui": "^0.2.14",
    "universal-vector-icons": "^4.4.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "0.52.2",
    "react-native-drawer": "^2.3.0",
    "react-native-web": "^0.5.4",
    "react-universal-ui": "^0.2.14",
    "universal-vector-icons": "^4.4.1"
  },
```

**Comment by cloudle** [comment]
@SeanFelipe yep, I guess you're using the boilerplate code (by git clone).. there was many many changes since that.. but I didn't update the documentation yet.

Basically, for now we should start with the `cli tool` instead:
```bash
npm i -g ruui-cli #install the cli once, similar to react-native-cli
ruui init <projectName> #to create new project with everything setted up in the right place
cd <projectName>
ruui dev #start the development server
```

**Comment by SeanFelipe** [comment]
Thanks ! I upgraded and am using `ruui dev` and we're fully operational :)
